name = "devlogic-website"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages"

[[build.upload]]
format = "directory"
dir = ".vercel/output/static"
